#!/usr/bin/env php

<?php
for($i=1;$i<count($argv);$i++){
     putenv($argv[$i]);
}

$defaultVendorPath = __DIR__ . '/../vendor';

defined('VENDOR_PATH') or define('VENDOR_PATH', getenv('VENDOR_PATH')?:$defaultVendorPath);
defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

/** @noinspection PhpIncludeInspection */
require(VENDOR_PATH . '/autoload.php');
/** @noinspection PhpIncludeInspection */
require(VENDOR_PATH . '/yiisoft/yii2/Yii.php');

$config = require(__DIR__ . '/config/console.php');
$application = new yii\console\Application($config);

exit($application->run());